name: Notify Discord on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is merged
      id: check_merged
      run: echo "::set-output name=merged::${{ github.event.pull_request.merged }}"

    - name: Notify Discord
      if: steps.check_merged.outputs.merged == 'true'
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{
          "content": "Pull Request **#${{ github.event.pull_request.number }}** has been merged! :tada:",
          "embeds": [
            {
              "title": "${{ github.event.pull_request.title }}",
              "url": "${{ github.event.pull_request.html_url }}",
              "description": "${{ github.event.pull_request.body }}",
              "color": 3066993,
              "fields": [
                {
                  "name": "Merged By",
                  "value": "${{ github.event.pull_request.merged_by.login }}"
                },
                {
                  "name": "State",
                  "value": "Merged"
                }
              ]
            }
          ]
        }' ${{ secrets.DISCORD_WEBHOOK }}
